export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const GET_AUTH_EVENT_SUCCESS = 'GET_AUTH_EVENT_SUCCESS';
export const ADD_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const GET_EVENT_CATEGORY = 'GET_EVENT_CATEGORY';

export const SUCCESSFUL_RSVP = 'SUCCESSFUL_RSVP';
